### PR TITLE
Feature/new leaderboard UI

### PR DESCRIPTION
**Pull request by ambid17**

### CODE REVIEW

**Comment by ambid17** [comment]
Steps to test:
- start a new game
- beat hop 1
- all of the Completion UI, and leaderboard UI should populate
- you should be able to switch between global and friends tab
- the UI should properly scale
- SOME of the leaderboard times should have checkboxes next to them. If you click on one, and hit replay...
- you should see a ghost. You should be able to hit G and spectate them. their name should show in the top right
- beat the level with the ghost, hit replay, it should now be YOUR ghost, spectate to confirm

Now, go to the main menu:
- go to level select
- the leaderboards should populate and global/friends tabs should work
- selecting a replay should load when you hit "play"

**Review by Vhostym — CHANGES_REQUESTED** [review]
Cannot unselect a ghost checkbox in the level select menu.

**Review by Vhostym — CHANGES_REQUESTED** [review]
When I beat a level (hop1 in this case) with a ghost active, it is still displaying that ghost when I reset the level, rather than my own.

Repro steps:
- Go to level select
- select hop 1
- select Sabien's run
- Spectate on ghost completing the run
- Complete the run yourself (with time slower than Sabien's)
- Hit R or select restart level

Sabien's ghost is still the active ghost in the run.

**Comment by ambid17** [comment]
this is intended functionality for now

**Pull request merged**
